stages:
  szte-metadata:
    cmd: make szte
    deps:
    - data/SZTE
    - src/ilids/models/szte.py
    - src/ilids/commands/szte
    - src/ilids/preprocessing/szte
    outs:
    - data/szte-metadata
  sztr-metadata:
    cmd: make sztr
    deps:
    - data/SZTR
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/preprocessing/sztr
    outs:
    - data/sztr-metadata
  ilids-metadata:
    cmd: make ilids
    deps:
    - data/SZTE
    - data/SZTR
    - src/ilids/models/szte.py
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/commands/szte
    - src/ilids/commands/ilids_aggregate
    - src/ilids/preprocessing/szte
    - src/ilids/preprocessing/sztr
    outs:
    - data/ilids-metadata
  extract-all-sequences:
    cmd: make -j$(make cpu_count) extract-all-sequences
    deps:
    - data/SZTE
    - data/SZTR
    - data/ilids-metadata
    - src/ilids/commands/videos/frames_extraction.py
    outs:
    - data/sequences
