stages:
  szte-metadata:
    cmd: make szte
    deps:
    - data/SZTE
    - src/ilids/models/szte.py
    - src/ilids/commands/szte
    - src/ilids/preprocessing/szte
    outs:
    - data/szte-metadata:
        cache: false
  sztr-metadata:
    cmd: make sztr
    deps:
    - data/SZTR
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/preprocessing/sztr
    outs:
    - data/sztr-metadata:
        cache: false
  ilids-metadata:
    cmd: make ilids
    deps:
    - data/SZTE
    - data/SZTR
    - src/ilids/models/szte.py
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/commands/szte
    - src/ilids/commands/ilids_aggregate
    - src/ilids/preprocessing/szte
    - src/ilids/preprocessing/sztr
    outs:
    - data/ilids-metadata:
        cache: false
  tp-fp-sequences:
    cmd: make sequences
    deps:
    - data/handcrafted-metadata/szte_distractions.extended.corrected.csv
    - notebooks/generate-sequences-alarms-FP.ipynb
    - data/ilids-metadata/alarms.csv
    - data/ilids-metadata/clips.csv
    - data/ilids-metadata/videos.csv
    outs:
    - data/handcrafted-metadata/tp_fp_sequences.csv:
        cache: false
  extract-all-sequences:
    cmd: make -j$(make cpu_count) extract-all-sequences
    deps:
    - data/SZTE
    - data/SZTR
    - data/handcrafted-metadata/tp_fp_sequences.csv
    - src/ilids/commands/videos/frames_extraction.py
    outs:
    - data/sequences:
        persist: true

  results-features-movinet:
    cmd: make -j$(make cpu_count) results-features-movinet
    deps:
    - data/sequences
    outs:
    - results/movinet
