stages:
  szte-metadata:
    cmd: make szte
    deps:  # find src scripts -name "*szte*" -not -path "*/__pycache__/*"
    - SZTE
    - src/ilids/models/szte.py
    - src/ilids/commands/szte
    - src/ilids/preprocessing/szte
    outs:
    - data/szte-metadata
  sztr-metadata:
    cmd: make sztr
    deps:  # find src scripts -name "*sztr*" -not -path "*/__pycache__/*"
    - SZTE
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/preprocessing/sztr
    outs:
    - data/sztr-metadata
  ilids-metadata:
    cmd: make ilids
    deps:
    - SZTE
    - SZTR
    - src/ilids/models/szte.py
    - src/ilids/models/sztr.py
    - src/ilids/commands/sztr
    - src/ilids/commands/szte
    - src/ilids/commands/ilids_indexes.py
    - src/ilids/commands/ilids_videos.py
    - src/ilids/preprocessing/szte
    - src/ilids/preprocessing/sztr
    outs:
    - data/ilids-metadata
  sequences:
    cmd: make sequences
    deps:
    - notebooks/generate-sequences-alarms-FP.ipynb
    - data/handcrafted-metadata/szte_distractions.extended.corrected.csv
    - data/ilids-metadata/alarms.csv
    - data/ilids-metadata/clips.csv
    - data/ilids-metadata/videos.csv
    outs:
    - data/handcrafted-metadata/tp_fp_sequences.csv
