# generated by datamodel-codegen:
#   filename:  index-library.tmp.json
#   timestamp: 2022-08-14T13:21:26+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel


class AlarmItem(BaseModel):
    AlarmDescription: str
    AlarmDuration: str
    Distance: str
    StartTime: str
    SubjectApproachType: str
    SubjectDescription: str
    SubjectOrientation: str


class Alarms(BaseModel):
    Alarm: List[AlarmItem]


class Distractions(BaseModel):
    Distraction: Union[str, List[str]]


class Weather(BaseModel):
    Clouds: Optional[str] = None
    Fog: str
    Rain: str
    Snow: str
    TimeOfDay: str


class ClipItem(BaseModel):
    AlarmEvents: str
    Alarms: Optional[Alarms] = None
    Distractions: Optional[Distractions] = None
    Duration: str
    Stage: str
    Weather: Weather
    filename: str


class IlidsLibrary(BaseModel):
    clip: List[ClipItem]
    dataset: str
    libversion: str
    scenario: str
